sudo: true

language: python

python:
  - "3.6"

node_js:
  - "8"

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
  - pip install -U pip

install:
  - pip install Flask-Restless
  - pip install Flask-SQLAlchemy
  - pip install PyMySQL
  - pip install ratelimit
  - pip install coverage
  - npm install

script:
  - coverage run data/test.py
