

const Card = {
  main: {
    padding: '10px 10px 10px 10px',
    width: '256px',
    webkitTransform: 'translateZ(0)',
    mozTransform: 'translateZ(0)',
    msTransform: 'translateZ(0)',
    oTransform: 'translateZ(0)',
    transform: 'translateZ(0)',
    willChange: 'transform',
  },

  card: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderRadius: '10px',
    backgroundColor: 'darkgray',
    webkitTransition: '-webkit-transform 0.2s, -webkit-filter 0.1s',
    mozTransition: '-moz-transform 0.2s, -moz-filter 0.1s',
    msTransition: '-ms-transform 0.2s, -ms-filter 0.1s',
    oTransition: '-o-transform 0.2s, -o-filter 0.1s',
    transition: 'transform 0.2s, filter 0.1s',
    webkitTransform: 'scale(1.0)',
    mozTransform: 'scale(1.0)',
    msTransform: 'scale(1.0)',
    oTransform: 'scale(1.0)',
    transform: 'scale(1.0)',
    ':hover': {
      webkitTransition: '-webkit-transform 0.2s, -webkit-filter 0.5s',
      mozTransition: '-moz-transform 0.2s, -moz-filter 0.5s',
      msTransition: '-ms-transform 0.2s, -ms-filter 0.5s',
      oTransition: '-o-transform 0.2s, -o-filter 0.5s',
      transition: 'transform 0.2s, filter 0.5s',
      webkitTransform: 'scale(0.98)',
      mozTransform: 'scale(0.98)',
      msTransform: 'scale(0.98)',
      oTransform: 'scale(0.98)',
      transform: 'scale(0.98)',
      webkitFilter: 'hue-rotate(360deg)',
      mozFilter: 'hue-rotate(360deg)',
      msFilter: 'hue-rotate(360deg)',
      oFilter: 'hue-rotate(360deg)',
      filter: 'hue-rotate(360deg)',
    },

    clicked: {
      webkitFilter: 'brightness(0.5) hue-rotate(360deg)',
      mozFilter: 'brightness(0.5) hue-rotate(360deg)',
      msFilter: 'brightness(0.5) hue-rotate(360deg)',
      oFilter: 'brightness(0.5) hue-rotate(360deg)',
      filter: 'brightness(0.5) hue-rotate(360deg)',
    },
  },

  tooltip: {
    display: 'flex',
    position: 'fixed',
    backgroundColor: 'black',
    width: '100%',
    height: '100%',
    top: '0',
    left: '0',
    padding: '0px 5% 0px 5%',
    borderBottomLeftRadius: '10px',
    borderBottomRightRadius: '10px',
    webkitTransition: 'opacity 0.25s ease-out',
    mozTransition: 'opacity 0.25s ease-out',
    msTransition: 'opacity 0.25s ease-out',
    oTransition: 'opacity 0.25s ease-out',
    transition: 'opacity 0.25s ease-out',
    opacity: '0.0',
    ':hover': {
      zIndex: '100',
      height: '100%',
      opacity: '1.0',
      color: 'white',
      webkitTransition: 'opacity 0.125s ease-in',
      mozTransition: 'opacity 0.125s ease-in',
      msTransition: 'opacity 0.125s ease-in',
      oTransition: 'opacity 0.125s ease-in',
      transition: 'opacity 0.125s ease-in',
      textShadow: '0px 0px 2px gray, 0px 0px 3px black',
    },
  },
  imageContainerContainer: {
    backgroundColor: 'darkGray',
    height: '256px',
    ':hover': {
      backgroundColor: 'darkGray',
    },
  },

  imageContainer: imageURL => ({
    overflow: 'hidden',
    borderRadius: '10px',
    webkitTransition: '-webkit-transform 0.2s',
    mozTransition: '-moz-transform 0.2s',
    msTransition: '-ms-transform 0.2s',
    oTransition: '-o-transform 0.2s',
    transition: 'transform 0.2s',
    webkitTransform: 'scale(0.995)',
    mozTransform: 'scale(0.995)',
    msTransform: 'scale(0.995)',
    oTransform: 'scale(0.995)',
    transform: 'scale(0.995)',
    objectFit: 'fill',
    margin: 'auto',
    display: 'flex',
    verticalAlign: 'middle',
    height: '100%',
    objectFit: 'fill',
    backgroundPosition: 'center',
    backgroundSize: '100% 100%',
    ':hover': {
      webkitTransform: 'scale(1.0)',
      mozTransform: 'scale(1.0)',
      msTransform: 'scale(1.0)',
      oTransform: 'scale(1.0)',
      transform: 'scale(1.0)',
      backgroundColor: 'darkgray',
    },
  }),

  backgroundImage: {
    position: 'fixed',
    webkitFilter: 'blur(64px)',
    mozFilter: 'blur(64px)',
    oFilter: 'blur(64px)',
    msFilter: 'blur(64px)',
    filter: 'blur(64px)',
    top: '-50%',
    left: '-50%',
    backgroundColor: 'white',
    margin: 'auto',
    width: '200%',
    height: '200%',
    zIndex: '1',
  },

  image: {
    maxWidth: '100%',
    borderRadius: '0px',
    webkitTransition: '-webkit-transform 0.2s, -webkit-filter 0.2s',
    mozTransition: '-moz-transform 0.2s, -moz-filter 0.2s',
    msTransition: '-ms-transform 0.2s, -ms-filter 0.2s',
    oTransition: '-o-transform 0.2s, -o-filter 0.2s',
    transition: 'transform 0.2s, filter 0.2s',
    webkitTransform: 'scale(1.0)',
    mozTransform: 'scale(1.0)',
    msTransform: 'scale(1.0)',
    oTransform: 'scale(1.0)',
    transform: 'scale(1.0)',
    margin: 'auto',
    verticalAlign: 'middle',
    zIndex: '2',
    ':hover': {
      webkitTransition: '-webkit-transform 1.0s, -webkit-filter 1.0s',
      mozTransition: '-moz-transform 1.0s, -moz-filter 1.0s',
      msTransition: '-ms-transform 1.0s, -ms-filter 1.0s',
      oTransition: '-o-transform 1.0s, -o-filter 1.0s',
      transition: 'transform 1.0s, filter 1.0s',
      webkitTransform: 'scale(1.05)',
      mozTransform: 'scale(1.05)',
      msTransform: 'scale(1.05)',
      oTransform: 'scale(1.05)',
      transform: 'scale(1.05)',
    },
  },


  captionContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: '2% 5% 2% 0%',
    webkitTransition: 'height 0.2s',
    mozTransition: 'height 0.2s',
    msTransition: 'height 0.2s',
    oTransition: 'height 0.2s',
    transition: 'height 0.2s',
    ':hover': {
      height: '0px',
      overflow: 'hidden',
    },
  },

  caption: {
    maxWidth: '65%',
    postion: 'relative',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },

  badgeContainer: {
    maxWidth: '35%',
  },
};

export default Card;
